/******************************************************************************
 *
 * Module: Ultrasonic
 *
 * File Name: Ultrasonic_Driver.c
 *
 * Description: Source file for the Ultrasonic Sensor
 *
 * Author: Mohanad Adel
 *
 *******************************************************************************/

#include "Ultrasonic_Driver.h"


/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/
uint8 g_edgeCount = 0;
uint16 g_timeHigh = 0;
uint16 g_timePeriod = 0;
uint16 g_timePeriodPlusHigh = 0;

/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/
/*
 * Description : Function to initialize the Ultrasonic driver
 * 	1. Initialize the ICU Driver as required
 * 	2. Setup the ICU Callback Function
 * 	3. Setup the direction for the trigger pin as output pin through the GPIO driver
 */
void Ultrasonic_init(void)
{
	/* Setup the Trigger Pin Direction */
	GPIO_setupPinDirection(US_TRIGGER_PORT, US_TRIGGER_PIN, PIN_OUTPUT);

	/* Set the Call back function pointer in the ICU driver */
	ICU_setCallBack(Ultrasonic_edgeProcessing);

	/* Create configuration structure for ICU driver */
	ICU_ConfigType ICU_Config = {F_CPU_8, RISING};

	/* Initialize ICU driver */
	ICU_init(&ICU_Config);

	/* Enable Global Interrupt I-Bit */
	//SREG |= (1<<7);

}


/*
 * Description : Function to give 10us trigger pulse on trigger pin
 * 	1. Send the Trigger pulse to the Ultrasonic
 */
void Ultrasonic_Trigger(void)
{
	GPIO_writePin(US_TRIGGER_PORT, US_TRIGGER_PIN, LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(US_TRIGGER_PORT, US_TRIGGER_PIN, LOGIC_LOW);
}


/*
 * Description : Function to read distance of the Ultrasonic
 * 	1. Send the trigger pulse by using Ultrasonic_Trigger function
 * 	2. Start the measurements by the ICU from this moment
 *  3. Return the measured distance in cm
 */
uint16 Ultrasonic_readDistance(void)
{
	uint16 distance;
	Ultrasonic_Trigger();		/* Send 10us Pulse to the Trigger Pin */

	Ultrasonic_init();			/* Call the init function to recalculate distance */

	distance = ((float64)(g_timePeriodPlusHigh - g_timeHigh) * 0.017);		/* Calculate the Distance */

	return distance;
}


/*
 * Description : Function to initialize the Ultrasonic driver
 * 	1. This is the call back function called by the ICU driver
 * 	2. This is used to calculate the high time (pulse time) generated by the ultrasonic sensor
 */
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		ICU_clearTimerValue();
		/* Detect falling edge */
		ICU_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_timeHigh = ICU_getInputCaptureValue();
		/* Detect rising edge */
		ICU_setEdgeDetectionType(RISING);
	}
	else if(g_edgeCount == 3)
	{
		/* Store the Period time value */
		g_timePeriod = ICU_getInputCaptureValue();
		/* Detect falling edge */
		ICU_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 4)
	{
		/* Store the Period time value + High time value */
		g_timePeriodPlusHigh = ICU_getInputCaptureValue();
		/* Clear the timer counter register to start measurements again */
		ICU_clearTimerValue();
		/* Detect rising edge */
		ICU_setEdgeDetectionType(RISING);
	}
}

